# Generated by Django 3.0.2 on 2020-01-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('landline', models.CharField(max_length=200)),
                ('email_1', models.CharField(max_length=200)),
                ('email_2', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('referral', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
