# Generated by Django 3.0.2 on 2020-01-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='address_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
