# Generated by Django 3.0.2 on 2020-01-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200119_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
