# Generated by Django 3.0.2 on 2020-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=25)),
                ('option_name', models.CharField(max_length=25)),
                ('product_id', models.CharField(max_length=25)),
                ('unit_price', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TrsNatte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_hieght', models.CharField(max_length=25)),
                ('trs_24', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_28', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_32', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_36', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_40', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_44', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_48', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_52', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_56', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_60', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_64', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_68', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_72', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_76', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_80', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_84', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_88', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_92', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_96', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_100', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_104', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trs_108', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
